sonar.projectKey=lightlivermorium_middle-nodejs-project-4
sonar.organization=lightlivermorium

sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**

sonar.tests=__tests__
sonar.test.inclusions=__tests__/**/*.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info
